stages:
  - test
  - build

node-test:
  image: node:23
  stage: test
  services:
    - name: registry.gitlab.com/fullrestore/fullrestore-database:latest
      alias: postgres
  variables:
    POSTGRES_DB: fullrestore-migration-test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: 0.0.0.0
    DB_HOST: postgres
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASSWORD: password
    NODE_ENV: test
    CI_ENV: "true"
  script:
    - npm ci
    - apt-get update && apt-get install -y netcat-openbsd
    - nc -zv postgres 5432
    - cd packages/migration && npx sequelize-cli db:migrate
  rules:
    - if: $CI_COMMIT_BRANCH

docker-build:
  # Use the official docker image.
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - cd packages/api
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  only:
    - tags
    - main