stages:
  - test
  - build
  - publish

include:
  - local: packages/.gitlab-ci.yml
  - local: packages/service/.gitlab-ci.yml

publish-packages:
  stage: publish
  script:
    - echo "Coordinating package publishing"
  only:
    - tags
    - main
  when:
    manual

build-containers:
  stage: build
  script:
    - echo "Coordinating api container building"
  only:
    - tags