image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm config set -- //gitlab.com/api/v4/projects/66553564/packages/npm/:_authToken="${NPM_TOKEN}"
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc

    - npm install -y
    - npm publish --verbose
  environment: production