image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm config set -- //gitlab.com/api/v4/projects/66553564/packages/npm/:_authToken="${NPM_TOKEN}"
    - echo "@sean64roche:fullrestore-service=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm install -y
    - npm publish --verbose
  environment: production