image: node:latest

stages:
  - build

publish-package:
  stage: build
  script:
    - npm install -y
    - npm config set -- //gitlab.com/api/v4/projects/66637031/packages/npm/:_authToken="${NPM_TOKEN}"
    - echo "@fullrestore:registry=https://gitlab.com/api/v4/projects/66637031/packages/npm/" > .npmrc
    - npm publish