stages:
  - test
  - build
  - deploy
  - publish

include:
  - local: packages/api/.gitlab-ci.yml
  - local: packages/service/.gitlab-ci.yml

publish-packages:
  stage: publish
  script:
    - echo "Coordinating package publishing"
  only:
    - tags

build-containers:
  stage: build
  script:
    - echo "Coordinating api container publishing"
  only:
    - tags