image: node:latest

stages:
  - build

publish-package:
  stage: build
  script:
    - npm ci
    - npm config set -- //gitlab.com/api/v4/projects/66637031/packages/npm/:_authToken="${NPM_TOKEN}"
    - echo "@fullrestore:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish --verbose
  only:
    - tags
    - main